- name: Create a login user
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - sudo
      - users
    state: present
    append: true
    shell: "{{ user_shell }}"
    update_password: on_create

- name: Ensure group "{{ username }}" exists
  group:
    name: "{{ username }}"
    state: present

- name: Chmod the user home directory
  file:
    path: "/home/{{ username }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Copy the Ansible playbook to the new user
  copy:
    src: "/root/ansible-easy-vpn"
    dest: "/home/{{ username }}/ansible-easy-vpn"
    recusrse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
